org.gradle.jvmargs=-Xmx4G
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# Setting newDsl to true for compatibility with modern AGP versions
android.newDsl=true
systemProp.ANDROID_USER_HOME=C\:\\Users\\summi\\.android
systemProp.ANDROID_PREFS_ROOT=C\:\\Users\\summi\\.android
